export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";

export const FETCH_DETAILS_REQUEST = "FETCH_DETAILS_REQUEST";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_FAILURE = "FETCH_DETAILS_FAILURE";

export const ADD_TO_FAVORITE_LIST = "ADD_TO_FAVORITE_LIST";

export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
